create extension if not exists pgcrypto;

do $$ begin
  create type public.app_id as enum ('web', 'geeta_nexus', 'nexus_plus');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.platform as enum ('web', 'ios', 'android');
exception when duplicate_object then null; end $$;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  google_sub text unique,
  email text not null unique,
  name text,
  picture text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_devices (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  app_id public.app_id not null,
  platform public.platform not null,
  push_token text unique,
  origin text,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  target_channel text not null,
  title text not null,
  message text not null,
  action_url text,
  broadcast_type text not null default 'unified_event',
  created_at timestamptz not null default now()
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint references public.notifications(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  app_id public.app_id not null,
  provider text not null default 'expo',
  push_token text,
  status text not null default 'pending',
  provider_ticket_id text,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists user_devices_app_idx on public.user_devices(app_id);
create index if not exists notification_deliveries_status_idx on public.notification_deliveries(status, created_at desc);

alter table public.users enable row level security;
alter table public.user_devices enable row level security;
alter table public.notifications enable row level security;
alter table public.notification_deliveries enable row level security;

revoke all on public.users from anon, authenticated;
revoke all on public.user_devices from anon, authenticated;
revoke all on public.notification_deliveries from anon, authenticated;

drop policy if exists public_notifications_read on public.notifications;
create policy public_notifications_read on public.notifications for select to anon, authenticated using (true);

-- Backend uses the Supabase service role for verified writes. No private key belongs in this script.
