import { useEffect, useState } from "react";
import { Link } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useAuth } from "@/context/AuthContext";
import { supabase } from "@/lib/supabase";
import { Loader2, ShieldAlert } from "lucide-react";

export default function Admin() {
  const { user, isLoading } = useAuth();
  const [tab, setTab] = useState<"post" | "app" | "banner">("post");
  const [message, setMessage] = useState("");
  const [post, setPost] = useState({ title: "", slug: "", excerpt: "", content: "", category: "" });
  const [app, setApp] = useState({ name: "", slug: "", description: "", version: "", platform: "", download_url: "" });
  const [banner, setBanner] = useState({ title: "", body: "", kind: "banner" });
  useEffect(() => { if (user && !user.isAdmin) setMessage("This account does not have publishing permissions."); }, [user]);
  if (isLoading) return <div className="min-h-[60vh] grid place-items-center"><Loader2 className="animate-spin" /></div>;
  if (!user) return <main className="min-h-[60vh] grid place-items-center"><div className="text-center"><h1 className="text-3xl">Sign in required</h1><Button asChild className="mt-5"><Link href="/login">Sign in</Link></Button></div></main>;
  if (!user.isAdmin) return <main className="min-h-[60vh] grid place-items-center"><div className="text-center"><ShieldAlert className="mx-auto h-10 w-10 text-destructive" /><h1 className="mt-4 text-3xl">Access denied</h1><p className="mt-2 text-muted-foreground">{message}</p></div></main>;
  async function save(event: React.FormEvent) { event.preventDefault(); setMessage(""); const result = tab === "post" ? await supabase.from("posts").insert({ ...post, published: true, published_at: new Date().toISOString() }) : tab === "app" ? await supabase.from("apps").insert({ ...app, published: true }) : await supabase.from("app_ui_config").insert({ ...banner, enabled: true }); if (result.error) setMessage(result.error.message); else { setMessage("Saved successfully."); if (tab === "post") setPost({ title: "", slug: "", excerpt: "", content: "", category: "" }); } }
  return <main className="mx-auto max-w-5xl px-6 py-16"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">Private workspace</p><h1 tabIndex={-1} className="mt-3 text-5xl">Admin studio</h1><p className="mt-3 text-muted-foreground">Publish website content and control the native app without an app update.</p></div><Button variant="outline" asChild><Link href="/">View site</Link></Button></div><div className="mt-12 flex gap-2 border-b border-border">{(["post", "app", "banner"] as const).map(item => <button key={item} onClick={() => setTab(item)} className={`px-4 py-3 text-sm capitalize ${tab === item ? "border-b-2 border-primary font-semibold" : "text-muted-foreground"}`}>{item === "post" ? "Blog post" : item === "app" ? "App listing" : "App alert"}</button>)}</div><form onSubmit={save} className="mt-10 max-w-2xl space-y-5">{tab === "post" && <><Field label="Title" value={post.title} onChange={v => setPost({ ...post, title: v })} /><Field label="Slug" value={post.slug} onChange={v => setPost({ ...post, slug: v })} /><Field label="Category" value={post.category} onChange={v => setPost({ ...post, category: v })} /><Field label="Excerpt" value={post.excerpt} onChange={v => setPost({ ...post, excerpt: v })} /><div><Label>Content</Label><Textarea required value={post.content} onChange={e => setPost({ ...post, content: e.target.value })} className="mt-2 min-h-48" /></div></>}{tab === "app" && <><Field label="App name" value={app.name} onChange={v => setApp({ ...app, name: v })} /><Field label="Slug" value={app.slug} onChange={v => setApp({ ...app, slug: v })} /><Field label="Platform" value={app.platform} onChange={v => setApp({ ...app, platform: v })} /><Field label="Version" value={app.version} onChange={v => setApp({ ...app, version: v })} /><Field label="Download URL" value={app.download_url} onChange={v => setApp({ ...app, download_url: v })} /><div><Label>Description</Label><Textarea value={app.description} onChange={e => setApp({ ...app, description: e.target.value })} className="mt-2" /></div></>}{tab === "banner" && <><Field label="Title" value={banner.title} onChange={v => setBanner({ ...banner, title: v })} /><div><Label>Message</Label><Textarea required value={banner.body} onChange={e => setBanner({ ...banner, body: e.target.value })} className="mt-2" /></div></>} {message && <p className="text-sm text-muted-foreground">{message}</p>}<Button type="submit">Publish {tab}</Button></form></main>;
}
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div><Label>{label}</Label><Input required value={value} onChange={e => onChange(e.target.value)} className="mt-2 h-11" /></div>; }
