import { useMemo, useState } from "react";
import { ArrowRight, CheckCircle2, Command, Download, FileText, Image as ImageIcon, LayoutGrid, Link2, Menu, Search, Scissors, Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import NexusToolWorkspace, { NEXUS_TOOLS } from "@/components/NexusToolWorkspace";
import { useLocation } from "wouter";

type ToolId = (typeof NEXUS_TOOLS)[number]["id"];
const categories = ["All tools", "Audio", "Documents", "Images", "Writing", "Utilities"];

export default function Home() {
  const [, navigate] = useLocation();
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All tools");
  const [selectedTool, setSelectedTool] = useState<ToolId | null>(null);
  const [nativeMode] = useState(() => new URLSearchParams(window.location.search).has("app") || new URLSearchParams(window.location.search).has("native"));
  const filteredTools = useMemo(() => NEXUS_TOOLS.filter((tool) => (category === "All tools" || tool.category === category) && `${tool.name} ${tool.description}`.toLowerCase().includes(query.toLowerCase())), [category, query]);

  if (selectedTool) return <div className="bg-background px-4 py-10 md:px-8"><NexusToolWorkspace selectedTool={selectedTool} onClear={() => setSelectedTool(null)} /></div>;

  return <div className="min-h-screen bg-background text-foreground">
    {!nativeMode && <header className="border-b border-border"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 md:px-8"><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="flex items-center gap-3 font-bold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Command className="size-5" /></span><span>NEXUS WAVE <span className="text-muted-foreground">/ TOOLS</span></span></button><nav className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#tools" className="hover:text-foreground">Tools</a><a href="#why" className="hover:text-foreground">Why Nexus</a><a href="mailto:hello@nexuswave.in" className="hover:text-foreground">Contact</a></nav><Button variant="outline" size="sm" onClick={() => navigate("/login")}><Sparkles data-icon="inline-start" />Sign in</Button></div></header>}
    <main>
      <section className="mx-auto max-w-6xl px-4 pb-14 pt-16 md:px-8 md:pb-20 md:pt-24"><div className="max-w-3xl"><Badge variant="outline" className="mb-5 gap-2 border-primary/30 bg-primary/5 text-primary"><span className="size-2 rounded-full bg-primary" />Nexus Wave Technologies</Badge><h1 className="text-balance text-4xl font-bold leading-tight tracking-tight md:text-6xl">Useful tools.<br /><span className="text-primary">No friction.</span></h1><p className="mt-6 max-w-2xl text-pretty text-base leading-7 text-muted-foreground md:text-lg">Fast, private browser utilities for everyday work. Built to be accessible, lightweight, and ready when you are.</p></div><div className="mt-10 flex max-w-2xl items-center gap-3 rounded-2xl border border-border bg-card p-2 shadow-sm"><Search className="ml-3 size-5 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tools..." className="h-11 border-0 bg-transparent shadow-none focus-visible:ring-0" /><kbd className="hidden rounded-lg bg-muted px-2 py-1 font-mono text-xs text-muted-foreground sm:block">⌘ K</kbd></div></section>
      <section id="tools" className="border-y border-border bg-card"><div className="mx-auto max-w-6xl px-4 py-10 md:px-8"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="font-mono text-xs uppercase tracking-[0.18em] text-primary">The toolkit</p><h2 className="mt-2 text-2xl font-bold">Tools that get out of the way.</h2></div><div className="flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${category === item ? "border-primary bg-primary text-primary-foreground" : "border-border text-muted-foreground hover:text-foreground"}`}>{item}</button>)}</div></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filteredTools.map((tool) => { const Icon = tool.icon; return <button key={tool.id} onClick={() => setSelectedTool(tool.id)} className="group flex min-h-52 flex-col justify-between rounded-2xl border border-border bg-background p-5 text-left transition-all hover:-translate-y-1 hover:border-primary/50 hover:shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><div className="flex items-start justify-between"><span className={`grid size-11 place-items-center rounded-xl bg-primary/10 text-primary`}><Icon className="size-5" /></span><ArrowRight className="size-5 text-muted-foreground transition-transform group-hover:translate-x-1 group-hover:text-primary" /></div><div><Badge variant="secondary" className="mb-3 text-[10px] uppercase tracking-wider">{tool.category}</Badge><h3 className="font-bold">{tool.name}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{tool.description}</p></div></button> })}</div>{filteredTools.length === 0 && <div className="rounded-2xl border border-dashed border-border p-10 text-center text-muted-foreground">No tools match that search.</div>}</div></section>
      <section id="why" className="mx-auto grid max-w-6xl gap-8 px-4 py-16 md:grid-cols-3 md:px-8 md:py-24"><div className="md:col-span-1"><p className="font-mono text-xs uppercase tracking-[0.18em] text-primary">Why Nexus</p><h2 className="mt-3 text-3xl font-bold">Your files stay yours.</h2></div><div className="grid gap-5 md:col-span-2 md:grid-cols-3"><div><CheckCircle2 className="size-5 text-primary" /><h3 className="mt-4 font-bold">Private by default</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Core processing happens locally in your browser.</p></div><div><Download className="size-5 text-primary" /><h3 className="mt-4 font-bold">No install needed</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Open a tool, do the work, download the result.</p></div><div><LayoutGrid className="size-5 text-primary" /><h3 className="mt-4 font-bold">Made for everyone</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Keyboard-friendly, responsive, and easy to understand.</p></div></div></section>
    </main>
    {!nativeMode && <footer className="border-t border-border px-4 py-7 md:px-8"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-3 text-xs text-muted-foreground md:flex-row"><span>© {new Date().getFullYear()} Nexus Wave Technologies</span><span>Built with care by Kuldeep Kumar Yadav</span></div></footer>}
  </div>;
}
